Support background images
Aloxaf/silicon pull request #114
Opened 2020-10-02 15:24 UTC by MinerChAI

This PR adds support for using images as a background
- Added `--background-image` option, it is a path to the background image
- Image is currently resized to fit (doesn't preserve aspect ratio)
- Takes 2.5 seconds with a 6000x4000 image (500ms with solid color), maybe there's a way to make it faster
- I'm a Rust newbie so my code can be bad, please let me know if there's a way to make it better

2020-10-02 15:27 UTC, MinerChAI commented
Oh, it didn't like my rustfmt config

2020-10-02 21:08 UTC, j0hnmeow commented
Just checked, the slow part is the `resize` function

2020-10-03 01:43 UTC, Aloxaf requested changes
Nice idea.

But please don't make too many unrelated changes like merge imports.

2020-10-03 01:43 UTC, Aloxaf commented on src/utils.rs
> +    DynamicImage, GenericImage, GenericImageView, Pixel, Rgb, Rgba, RgbaImage,
Please remove `Rgb` here since it will not be used.

2020-10-03 01:43 UTC, Aloxaf commented on src/config.rs
> +                Some(path) => Background::Image(image::open(path).unwrap().to_rgba()),
Please don't use unwrap here, change the returned type to Result<ShadowAdder, Error> and use the question mark instead.

2020-10-03 01:47 UTC, Aloxaf commented
> Takes 2.5 seconds with a 6000x4000 image (500ms with solid color), maybe there's a way to make it faster

It's not surprising, image-rs is a bit slow. You can try `FilterType::Nearest`, it should be faster but I am not sure whether its quality is acceptable.

2020-10-03 06:55 UTC, j0hnmeow commented
> > Takes 2.5 seconds with a 6000x4000 image (500ms with solid color), maybe there's a way to make it faster
> 
> 
> 
> It's not surprising, image-rs is a bit slow. You can try `FilterType::Nearest`, it should be faster but I am not sure whether its quality is acceptable.

It makes quality much worse but wins only about 200ms

2020-10-03 07:23 UTC, j0hnmeow commented
Huh… I didnt close it

2020-10-03 07:26 UTC, j0hnmeow commented
Ok I fixed it

2020-10-04 02:49 UTC, Aloxaf approved these changes

2020-10-04 02:49 UTC, Aloxaf commented
LGTM

2020-10-04 02:49 UTC, merged